global:
  scrape_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager's default port is 9093
            - workshop-logging-alertmanager-1:9093

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
#  external_labels:
#    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: [
        "workshop-logging-nginx-exporter-1:8080"
      ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [
        "workshop-logging-node-exporter-1:9100"
      ]

  - job_name: 'workshop-servers'
    static_configs:
      - targets: [
        'workshop-logging-server-1:8080',
        'workshop-logging-server-2:8080'
      ]
