global:
  scrape_interval: 10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
#  external_labels:
#    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: [
        'workshop-logging-server-1:8080',
        'workshop-logging-server-2:8080'
      ]

  - job_name: 'workshop-servers'
    static_configs:
      - targets: [
        'workshop-logging-server-1:8080',
        'workshop-logging-server-2:8080'
      ]
